import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowLeft, AlertTriangle, CreditCard, Smartphone, Building, Banknote, Loader2 } from 'lucide-react';
import Header from '@/components/layout/Header';
import { useCart } from '@/contexts/CartContext';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { toast } from 'sonner';

const paymentMethods = [
  { id: 'mpesa', name: 'M-Pesa', icon: Smartphone, color: 'text-red-500' },
  { id: 'emola', name: 'eMola', icon: Smartphone, color: 'text-orange-500' },
  { id: 'bank', name: 'Transferência Bancária', icon: Building, color: 'text-blue-500' },
  { id: 'cash', name: 'Dinheiro', icon: Banknote, color: 'text-green-500' },
];

const CheckoutPage: React.FC = () => {
  const { items, selectedTable, total, clearCart } = useCart();
  const { user } = useAuth();
  const navigate = useNavigate();
  
  const [paymentMethod, setPaymentMethod] = useState('');
  const [isUrgent, setIsUrgent] = useState(false);
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(false);

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('pt-MZ', { style: 'currency', currency: 'MZN', minimumFractionDigits: 0 }).format(price);
  };

  const handleSubmitOrder = async () => {
    if (!user || items.length === 0 || !paymentMethod) {
      toast.error('Por favor, selecione um método de pagamento');
      return;
    }

    setLoading(true);

    try {
      let tableId = null;
      if (selectedTable) {
        const { data: tableData } = await supabase
          .from('restaurant_tables')
          .select('id')
          .eq('number', selectedTable)
          .maybeSingle();
        tableId = tableData?.id;
      }

      const orderType = selectedTable ? 'table' : 'online';
      
      // Create order with new fields - order_ref is auto-generated by database trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          table_id: tableId,
          total,
          status: 'pending',
          order_type: orderType,
          is_urgent: isUrgent,
          payment_method: paymentMethod,
          payment_status: paymentMethod === 'cash' ? 'pending' : 'pending',
          notes: notes || null,
          estimated_delivery_time: new Date(Date.now() + (isUrgent ? 15 : 30) * 60000).toISOString(),
        } as any)
        .select('*, order_ref')
        .single();

      if (orderError) throw orderError;

      // Insert order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        menu_item_id: item.menu_item_id,
        quantity: item.quantity,
        unit_price: item.price,
        notes: item.notes,
      }));

      await supabase.from('order_items').insert(orderItems);

      // Update table status if applicable
      if (tableId) {
        await supabase.from('restaurant_tables').update({ status: 'occupied' }).eq('id', tableId);
      }

      clearCart();
      toast.success('Pedido realizado com sucesso!');
      navigate(`/pedido/${order.order_ref}`);
    } catch (error: any) {
      console.error('Checkout error:', error);
      toast.error(error.message || 'Erro ao criar pedido');
    } finally {
      setLoading(false);
    }
  };

  if (items.length === 0) {
    navigate('/cart');
    return null;
  }

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-6 pb-32">
        <Link to="/cart" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft size={20} /> Voltar ao carrinho
        </Link>

        <h1 className="text-2xl font-display font-bold mb-6">Finalizar Pedido</h1>

        {/* Order Summary */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }}
          className="card-elevated p-4 mb-6"
        >
          <h2 className="font-bold mb-3">Resumo do Pedido</h2>
          <div className="space-y-2 text-sm">
            {items.map((item) => (
              <div key={item.id} className="flex justify-between">
                <span>{item.quantity}x {item.name}</span>
                <span>{formatPrice(item.price * item.quantity)}</span>
              </div>
            ))}
            <div className="border-t pt-2 mt-2 font-bold flex justify-between text-lg">
              <span>Total</span>
              <span className="text-primary">{formatPrice(total)}</span>
            </div>
          </div>
          {selectedTable && (
            <p className="text-sm text-muted-foreground mt-3">Mesa: <strong>{selectedTable}</strong></p>
          )}
        </motion.div>

        {/* Urgent Order */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="card-elevated p-4 mb-6"
        >
          <div className="flex items-start gap-3">
            <Checkbox 
              id="urgent" 
              checked={isUrgent} 
              onCheckedChange={(checked) => setIsUrgent(checked as boolean)}
            />
            <div>
              <Label htmlFor="urgent" className="font-bold flex items-center gap-2 cursor-pointer">
                <AlertTriangle size={18} className="text-warning" />
                Pedido Urgente
              </Label>
              <p className="text-sm text-muted-foreground mt-1">
                Marque se precisar do pedido mais rápido (pode haver taxa adicional)
              </p>
            </div>
          </div>
        </motion.div>

        {/* Notes */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="card-elevated p-4 mb-6"
        >
          <Label htmlFor="notes" className="font-bold mb-2 block">Observações</Label>
          <Textarea 
            id="notes"
            placeholder="Alguma observação especial para o pedido?"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="min-h-[80px]"
          />
        </motion.div>

        {/* Payment Methods */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="card-elevated p-4 mb-6"
        >
          <h2 className="font-bold mb-4 flex items-center gap-2">
            <CreditCard size={20} />
            Método de Pagamento
          </h2>
          <RadioGroup value={paymentMethod} onValueChange={setPaymentMethod}>
            <div className="grid gap-3">
              {paymentMethods.map((method) => (
                <div key={method.id} className="flex items-center space-x-3">
                  <RadioGroupItem value={method.id} id={method.id} />
                  <Label htmlFor={method.id} className="flex items-center gap-3 cursor-pointer flex-1 p-3 rounded-lg hover:bg-muted transition-colors">
                    <method.icon className={method.color} size={24} />
                    <span className="font-medium">{method.name}</span>
                  </Label>
                </div>
              ))}
            </div>
          </RadioGroup>
        </motion.div>

        {/* Submit Button */}
        <div className="fixed bottom-0 left-0 right-0 p-4 bg-background border-t">
          <div className="container mx-auto">
            <Button 
              onClick={handleSubmitOrder} 
              disabled={loading || !paymentMethod}
              className="w-full"
              size="lg"
            >
              {loading ? (
                <>
                  <Loader2 className="animate-spin mr-2" size={20} />
                  Processando...
                </>
              ) : (
                `Confirmar Pedido • ${formatPrice(total)}`
              )}
            </Button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default CheckoutPage;
